### ISSUE TITLE
Support passing autobrr function {{.SizeString}} as the --limit param

### ISSUE THREAD

**Issue by danwilldev** [s0up4200/sizechecker#3]
Currently autobrr sends the size with a whitespace. Eg {{.SizeString}} = 12.5 GB
The util only accepts values without whitespace eg 12.5GB
So its throwing an error.
Maybe strip whitespace for this arg?

**Comment by danwilldev** [comment]
Currently working around the limitation using sprig --limit={{.SizeString | replace " " "" }}

**Comment by s0up4200** [comment]
Hey @danwilldev 👋 Will try to fix that tonight hopefully 👍

**Comment by s0up4200** [comment]
Should be good now! https://github.com/s0up4200/sizechecker/releases/tag/v1.2.0

**Comment by danwilldev** [comment]
Thanks for the quick turnaround 🎉🥂
